### ISSUE TITLE
Unicode properties may not be equivalent in JS

### ISSUE THREAD

**Issue by jaynetics** [slevithan/oniguruma-to-es#11]
Which properties exist, and which codepoints belong to a unicode property, can change with each Unicode version.

As a result, properties supported by the running Oniguruma version may not be supported by this library (or the targeted JS environment). Property names that are passed through and are supported on both sides may match too many chars (if the Unicode version of the JS engine is higher than that of Oniguruma), as well as too few (if the Unicode version of Oniguruma is higher). The same applies to POSIX classes.

js_regex deals with this by [interfacing with Onigmo's C API](https://github.com/jaynetics/regexp_property_values/blob/main/ext/regexp_property_values/regexp_property_values.c) to determine supported properties and currently matched codepoints, and emitting the codepoints as a character set. A downside of this is that these character sets can get very large.

**Comment by slevithan** [comment]
This is a good point to highlight, but note that there is no perfect solution, only tradeoffs. A tradeoff with `js_regex`'s approach is that the characters matched vary based on the version of Onigmo running on the server. Additionally, there are some cases where `js_regex` outputs Unicode properties directly (e.g. for `\X`, `\b`, or `\p{Hex}`) and the characters matched are then based on whatever version of Unicode is running in the JS environment where the generated regex is executed. And since `js_regex` doesn't restrict properties to those supported by the JS `target` specified, this can sometimes lead to runtime errors -- e.g. `\p{Gong}` is converted to `\p{Script=Gunjala_Gondi}` with target ES2018, but this script and its alias weren't added to JS until ES2019.

`oniguruma-to-es`'s readme [describes](https://github.com/slevithan/oniguruma-to-es#unicode) that the version of Unicode used is based on the JavaScript environment. Since this library is meant to be usable in browsers without any reliance on the server, this has the massive benefit of avoiding the inclusion of heavyweight Unicode character data. And IMO the downsides with differences in Unicode versions between Oniguruma and JS are extreme edge cases, since the latest version of Oniguruma (which is what this library targets) supports the quite-recent Unicode 15.1.0.

That said, I'm open to any suggestions for improvements (so long as they wouldn't lead to dramatically increasing the size of the library).

**Comment by slevithan** [comment]
Closing this since the current behavior is intentional, but happy to continue the discussion or reopen if helpful.

**Comment by slevithan** [comment]
That's a good idea, but yeah, JavaScript doesn't support that.
